CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    login VARCHAR(80) NOT NULL,
    senha_hash VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL,
    criado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    atualizado_em TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT usuario_login_key UNIQUE (login)
);

CREATE TABLE sessao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    turma VARCHAR(255) NOT NULL,
    data DATE NOT NULL,
    horario TIME NOT NULL,
    procurador VARCHAR(255) NOT NULL,
    sala VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    motivo_cancelamento VARCHAR(255),
    pauta_ordinaria VARCHAR(255),
    aditamentos VARCHAR(255),
    pauta_mesa VARCHAR(255),
    preferencias VARCHAR(255),
    criado_por BIGINT REFERENCES usuario(id),
    atualizado_por BIGINT REFERENCES usuario(id)
);
